n = input('Escreva alguma coisa:')
print('O tipo primitivo desse valor é {}'.format(type(n)))
print('Só possui espeços ? {}'.format(n.isspace()))
print('é um número ? {}'.format(n.isnumeric()))
print('É alfabético ? {}'.format(n.isalpha()))
print('É alfanúmerico ? {}'.format(n.isalnum()))
print('É maiúsculo por completo? {}'.format(n.islower()))
print('É minúsculo por completo? {}'.format(n.isupper()))
print('Ésta capitalizado ? {}'.format(n.istitle()))
