lista = list()
n1 = int(input('Digite um valor: '))
lista.append(n1)
n2 = int(input('Digite um segundo valor: '))
lista.append(n2)
n3 = int(input('Digite um  terceiro valor: '))
lista.append(n3)
lista.sort()
print(f'Maior valor: {lista[-1]}')
print(f'Menor valor: {lista[0]}')
